---
title: "giscoR"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{giscoR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(giscoR)


 # Different resolutions
 DNK_res60 <- gisco_get_countries(country_iso3 = "DNK")
 DNK_res20 <-
   gisco_get_countries(resolution = "20", country_iso3 = "DNK")
 DNK_res10 <-
   gisco_get_countries(resolution = "10", country_iso3 = "DNK")
 DNK_res03 <-
   gisco_get_countries(resolution = "03", country_iso3 = "DNK")

 opar <- par(no.readonly = TRUE)
 par(mfrow = c(2, 2), mar = c(3, 0, 2, 0))
 plot(st_geometry(DNK_res60), col = "red", main = "60M")
 plot(st_geometry(DNK_res20), col = "blue", main = "20M")
 plot(st_geometry(DNK_res10), col = "grey50", main = "10M")
 plot(st_geometry(DNK_res03), col = "black", main = "03M")
 title(sub = gisco_attributions(), line = 1)
 par(opar)

 # Different projections
 cntr_4326 <- gisco_get_countries(epsg = "4326")
 cntr_3857 <- gisco_get_countries(epsg = "3857")
 cntr_3035 <- gisco_get_countries(epsg = "3035")

 opar <- par(no.readonly = TRUE)
 par(mfrow = c(3, 1), mar = c(3, 0, 0, 0))
 plot(st_geometry(cntr_4326), graticule = TRUE)
 plot(
   st_geometry(cntr_3857),
   graticule = TRUE,
   ylim = c(-13000000, 13000000)
 )
 plot(st_geometry(cntr_3035), graticule = TRUE)
 title(sub = gisco_attributions(), line = 1)
 par(opar)

 
 # Labels and Lines available
 coast <- gisco_get_countries(spatialtype = "COASTL")
 labs <- gisco_get_countries(spatialtype = "LB")

 plot(st_geometry(coast), col = "blue1")
 plot(st_geometry(labs),
      col = "red",
      add = TRUE,
      pch = 19)

 title(sub = gisco_attributions(copyright = FALSE), line = 1)
 
 library(eurostat)
library(sf)
map <- gisco_get_nuts(year = "2016",
                      nuts_level = "2",
                      epsg = "3035")

#For the borders only
brds <- gisco_get_nuts(
  year = "2016",
  spatialtype = "BN",
  nuts_level = "0",
  epsg = "3035"
)

pps <- get_eurostat("tgs00026")
pps <- pps[grep("2016", pps$time),]

map.join <- merge(map,
                  pps,
                  by.x = "NUTS_ID",
                  by.y = "geo",
                  all.x = TRUE)

library(cartography)
br <- getBreaks(map.join$values, method = "jenks")

library(colorspace)
pal <- sequential_hcl(n = (length(br) - 1),
                      pal = "Inferno",
                      rev = TRUE)
opar <- par(no.readonly = TRUE)
par(mar = c(1, 1, 1, 1))
plot(
  st_geometry(map.join),
  col = NA,
  bg = "aliceblue",
  xlim = c(2200000, 7150000),
  ylim = c(1380000, 5500000)
)
choroLayer(
  map.join,
  var = "values",
  border = "grey60",
  breaks = br,
  col = pal,
  add = TRUE,
  legend.pos = "n"
)
plot(st_geometry(brds),
     col = "black",
     add = TRUE,
     lwd = 1.2)
att <- paste0("Data extracted from package eurostat \n",
              gisco_attributions(copyright = FALSE))

legendChoro(
  title.txt = NA,
  breaks = paste0(br / 1000, "K EUR"),
  col = pal
)
layoutLayer("Purchase Parity Power, NUTS 2 regions (2016)",
            col = pal[3],
            sources = att)
par(opar)



 
```
