---
title: "NUTS codes"
---

```{r knitropts, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  tidy = "styler",
  dev = "ragg_png",
  warning = FALSE,
  message = FALSE,
  out.width = "100%"
)

library(giscoR)
library(reactable)
```

Annex with the [NUTS codes](https://ec.europa.eu/eurostat/web/nuts/overview)
(version **2024**, **2021**, **2016** and **2013**) available in **giscoR**.

## NUTS 2024

```{r nuts24, echo=FALSE}
df <- gisco_get_nuts(year = 2024, resolution = 60)
df <- sf::st_drop_geometry(df)
reactable(df,
  elementId = "NUTS2024",
  filterable = TRUE,
  searchable = TRUE,
  defaultColDef = colDef(minWidth = 120),
  showPageSizeOptions = TRUE,
  striped = TRUE,
  paginationType = "jump",
  defaultSorted = c("LEVL_CODE", "CNTR_CODE")
)
```

## NUTS 2021

```{r nuts21, echo=FALSE}
df <- gisco_get_nuts(year = 2021, resolution = 60)
df <- sf::st_drop_geometry(df)
reactable(df,
  elementId = "NUTS2021",
  filterable = TRUE,
  searchable = TRUE,
  defaultColDef = colDef(minWidth = 120),
  showPageSizeOptions = TRUE,
  striped = TRUE,
  paginationType = "jump",
  defaultSorted = c("LEVL_CODE", "CNTR_CODE")
)
```

## NUTS 2016

```{r nuts16, echo=FALSE}
library(giscoR)
library(reactable)

df <- gisco_get_nuts(year = 2016, resolution = 60)
df <- sf::st_drop_geometry(df)
reactable(df,
  elementId = "NUTS2016",
  filterable = TRUE,
  searchable = TRUE,
  defaultColDef = colDef(minWidth = 120),
  showPageSizeOptions = TRUE,
  striped = TRUE,
  paginationType = "jump",
  defaultSorted = c("LEVL_CODE", "CNTR_CODE")
)
```

## NUTS 2013

```{r nuts13, echo=FALSE}
library(giscoR)
library(reactable)

df <- gisco_get_nuts(year = 2013, resolution = 60)
df <- sf::st_drop_geometry(df)
reactable(df,
  filterable = TRUE,
  searchable = TRUE,
  defaultColDef = colDef(minWidth = 120),
  showPageSizeOptions = TRUE,
  striped = TRUE,
  paginationType = "jump",
  defaultSorted = c("LEVL_CODE", "CNTR_CODE")
)
```
