# Workflow derived from https://github.com/r-devel/recheck
on:
    workflow_dispatch:
      inputs:
        which:
          type: choice
          description: Which dependents to check
          options:
          - strong
          - most

name: r-devel reverse dependency check

jobs:
    revdep_check:
      name: Reverse check ${{ inputs.which }} dependents
      uses: r-devel/recheck/.github/workflows/recheck.yml@v1
      with:
        which: ${{ inputs.which }}

