# Workflow derived from https://github.com/r-lib/actions/tree/master/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    branches: [main, master]
    tags: ['*']
  workflow_dispatch:

name: rogtemplate-gh-pages

jobs:
  rogtemplate-gh-pages:
    runs-on: windows-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: |
            local::.
            any::reactable
            ropengov/rogtemplate
          needs: website

      - name: Build logo if not present and prepare template
        run: |
          # Check that logo is not present
          if (isFALSE(file.exists(file.path("man", "figures", "logo.png")) ||
            file.exists(file.path("man", "figures", "logo.png")))) {
            rogtemplate::rog_logo()
          } else {

            message("The package already has a logo")
          }

          rogtemplate::rog_add_template_pkgdown()

        shell: Rscript {0}

      - name: Deploy package
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
          Rscript -e 'pkgdown::deploy_to_branch(new_process = TRUE, run_dont_run = TRUE, clear = TRUE)'

